CREATE DATABASE aprecat_db;

CREATE TABLE TABLE_CATS (

    CAT_ID INT NOT NULL AUTO_INCREMENT,
    CAT_NOME VARCHAR(50) NOT NULL,
    CAT_IDADE VARCHAR(2) NOT NULL,
    CONSTRAINT PK_Cat PRIMARY KEY (CAT_ID)

    );